"""Persistence for served requests.

One storage mechanism serves three purposes, which is why this exists at all:

1. The drift job needs a sample of recent request features to compare against
   the training reference distribution.
2. ``/stats`` needs request counts.
3. The backup/restore drill needs a table with real rows to prove row-count
   parity against.

``request_id`` is the primary key and is generated by the caller. That is what
makes a restore idempotent: re-inserting a restored row conflicts and is ignored
rather than duplicated. Without it, the restore drill would inflate the row
count it is supposed to be verifying.
"""

from __future__ import annotations

import json
import os
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

from sqlalchemy import (
    Float,
    Index,
    Integer,
    String,
    Text,
    create_engine,
    func,
    select,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column

from mlserve.config import ARTIFACTS

DEFAULT_URL = f"sqlite:///{(ARTIFACTS / 'mlserve.db').as_posix()}"


class Base(DeclarativeBase):
    pass


class RequestLog(Base):
    """One served prediction. Feature vector stored as JSON text."""

    __tablename__ = "requests"

    request_id: Mapped[str] = mapped_column(String(36), primary_key=True)
    created_at: Mapped[str] = mapped_column(String(32), nullable=False)
    runtime: Mapped[str] = mapped_column(String(32), nullable=False)
    batch_size: Mapped[int] = mapped_column(Integer, nullable=False)
    latency_ms: Mapped[float] = mapped_column(Float, nullable=False)
    predicted_class: Mapped[int] = mapped_column(Integer, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    features: Mapped[str] = mapped_column(Text, nullable=False)

    __table_args__ = (Index("ix_requests_created_at", "created_at"),)


def database_url() -> str:
    url = os.environ.get("MLSERVE_DATABASE_URL", DEFAULT_URL)
    if url.startswith("sqlite:///") and not url.startswith("sqlite:///:memory:"):
        Path(url.removeprefix("sqlite:///")).parent.mkdir(parents=True, exist_ok=True)
    return url


_engines: dict[str, Any] = {}
_initialised: set[str] = set()


def get_engine(url: str | None = None):
    url = url or database_url()
    if url not in _engines:
        # check_same_thread=False: FastAPI's TestClient and the threadpool both
        # touch this engine. SQLite handles its own locking.
        connect_args = {"check_same_thread": False} if url.startswith("sqlite") else {}
        _engines[url] = create_engine(url, future=True, connect_args=connect_args)
    return _engines[url]


def init_db(url: str | None = None) -> None:
    """Create tables, once per URL per process.

    The memo matters. This used to run ``create_all`` on every insert, putting a
    schema query on the hot write path - one of the two reasons the HTTP
    benchmark stalled at a few thousand rows. Called explicitly from the app
    lifespan and from tests rather than implicitly from every write.
    """
    resolved = url or database_url()
    if resolved in _initialised:
        return
    Base.metadata.create_all(get_engine(resolved))
    _initialised.add(resolved)


def reset_init_cache() -> None:
    """Forget which URLs have been initialised. Tests only."""
    _initialised.clear()


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="milliseconds")


def record_request(
    *,
    request_id: str,
    runtime: str,
    features: list[float],
    predicted_class: int,
    confidence: float,
    latency_ms: float,
    batch_size: int = 1,
    url: str | None = None,
) -> None:
    """Insert one row. Safe to call twice with the same id (restore idempotency)."""
    init_db(url)
    with Session(get_engine(url)) as session:
        if session.get(RequestLog, request_id) is not None:
            return
        session.add(
            RequestLog(
                request_id=request_id,
                created_at=_now(),
                runtime=runtime,
                batch_size=batch_size,
                latency_ms=latency_ms,
                predicted_class=predicted_class,
                confidence=confidence,
                features=json.dumps([round(float(v), 6) for v in features]),
            )
        )
        session.commit()


def count_requests(url: str | None = None) -> int:
    init_db(url)
    with Session(get_engine(url)) as session:
        return int(session.scalar(select(func.count()).select_from(RequestLog)) or 0)


def recent_features(
    limit: int = 2000,
    within_minutes: int | None = None,
    url: str | None = None,
) -> list[list[float]]:
    """Most recent feature vectors, oldest first.

    ``within_minutes`` bounds the window so the drift job compares like with
    like - a distribution pooled across a week hides a shift that started this
    morning.
    """
    init_db(url)
    statement = select(RequestLog.features).order_by(RequestLog.created_at.desc()).limit(limit)
    if within_minutes is not None:
        cutoff = (datetime.now(UTC) - timedelta(minutes=within_minutes)).isoformat(
            timespec="milliseconds"
        )
        statement = statement.where(RequestLog.created_at >= cutoff)
    with Session(get_engine(url)) as session:
        rows = list(session.scalars(statement))
    return [json.loads(row) for row in reversed(rows)]


def truncate(url: str | None = None) -> None:
    """Delete every row. Used by tests and by ``tasks.py clean``."""
    init_db(url)
    with Session(get_engine(url)) as session:
        session.query(RequestLog).delete()
        session.commit()


def prune(max_rows: int, url: str | None = None) -> int:
    """Delete the oldest rows so at most ``max_rows`` remain. Returns the count.

    Deliberately not called from the request write path. Doing a COUNT and a
    DELETE on every insert made writes quadratic in table size, which is exactly
    what stalled the HTTP benchmark. Pruning is maintenance: it belongs on a
    timer (the drift cron job calls this), not in the path a user waits on.
    """
    init_db(url)
    with Session(get_engine(url)) as session:
        total = int(session.scalar(select(func.count()).select_from(RequestLog)) or 0)
        excess = total - max_rows
        if excess <= 0:
            return 0
        stale = list(
            session.scalars(
                select(RequestLog.request_id).order_by(RequestLog.created_at.asc()).limit(excess)
            )
        )
        session.query(RequestLog).filter(RequestLog.request_id.in_(stale)).delete(
            synchronize_session=False
        )
        session.commit()
        return len(stale)
